spring:
  datasource:
    url: jdbc:mysql://localhost/petryshyn_lab3?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 20010123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: validate
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 3307
